### ISSUE TITLE
mpileup: invalid option -- 't'

### ISSUE THREAD

**Issue by juanjo255** [HarryHung/seroba#17]
Hello developers!

I using seroba v2.0.0 installed using python3 setup.py install (python 3.10)
kmc=3.1.2
mummer=3.23
bowtie2=2.5
ariba=2.14.6

I get the following error. I saw that this error in ariba was patched in [#327](https://github.com/sanger-pathogens/ariba/issues/327)

```

mpileup: invalid option -- 't'
Failed cluster: cluster
Traceback (most recent call last):
  File "/home/jjpiconc/.conda/envs/seroba/lib/python3.10/site-packages/ariba-2.14.6-py3.10-linux-x86_64.egg/ariba/clusters.py", line 612, in run
    self._run()
  File "/home/jjpiconc/.conda/envs/seroba/lib/python3.10/site-packages/ariba-2.14.6-py3.10-linux-x86_64.egg/ariba/clusters.py", line 646, in _run
    raise Error('At least one cluster failed! Stopping...')
ariba.clusters.Error: At least one cluster failed! Stopping...
```
I hope you can help me,

Thank you very much,

Juan

**Comment by juanjo255** [comment]
I installed ariba available in pipy which apparently is not updated with the last patched. It must be installed using source.
